import mongoose from "mongoose";

const timePlanSchema = new mongoose.Schema(
  {
    userId:    { type: String, required: true, index: true }, // auth0Id
    taskId:    { type: mongoose.Schema.Types.ObjectId, ref: "Task", default: null },
    taskTitle: { type: String, default: null },
    groupTag:  { type: String, default: "@personal" },
    categoryId:{ type: String, required: true, enum: ["work","learning","admin","health","personal","rest"] },

    // Planned window
    startTime: { type: Date, required: true, index: true },
    endTime:   { type: Date, required: true, index: true },

    notes:     { type: String, default: "" },
    status:    { type: String, enum: ["scheduled","in_progress","done","canceled"], default: "scheduled" },

    // Link to actual session created from this plan (optional)
    sessionId: { type: mongoose.Schema.Types.ObjectId, ref: "TimeSession", default: null },
    
    // Instance tracking (for recurring plans from task templates)
    // The specific date this plan instance represents (for recurring plans)
    instanceDate: {
      type: Date,
      required: false, // Optional for backward compatibility
      index: true,
      // Default will be derived from startTime if not provided
    },
    
    // Whether this was auto-generated from task template (vs manually created/edited)
    isAutoGenerated: {
      type: Boolean,
      default: false
    },
    
    // For auto-generated plans, track if user has overridden it
    isOverridden: {
      type: Boolean,
      default: false
    },
    
    // Original template values (for reference if overridden)
    templateStartTime: String, // "HH:MM"
    templateEndTime: String,    // "HH:MM"
  },
  { timestamps: true }
);

timePlanSchema.index({ userId: 1, startTime: 1 });
timePlanSchema.index({ userId: 1, status: 1, startTime: 1 });
timePlanSchema.index({ userId: 1, taskId: 1, instanceDate: 1 }); // For finding instances by task and date
timePlanSchema.index({ userId: 1, instanceDate: 1, isAutoGenerated: 1 }); // For cleanup queries

export default mongoose.model("TimePlan", timePlanSchema);